Task13
HelgiMagic/library pull request #10
Opened 2024-02-19 16:15 UTC by HelgiMagic

2024-02-21 12:15 UTC, vsmirnova requested changes

2024-02-21 12:15 UTC, vsmirnova commented on src/components/Book/Book.jsx
> +        <IconButton name="favorite" size="big" variant={constants.ICON_WITH_BACKGROUND} bg={bg} onClick={handleFavoriteClick} />
я бы переделала variant, на формат как size, передавать строку. А в компоненте через propTypes делать ограничение на варианты

2024-02-21 12:15 UTC, vsmirnova commented on src/components/Book/Book.jsx
>      </ui.BookWrapper>
Не нравится вот эта запись <ui.
В идеале, под каждый такой компонент делать отдельно папку. В корне папки ui можно сделать index.js с необходимыми экспортами и тут в импорте писать {Title, BookWrapper} from './ui'

2024-02-21 12:15 UTC, vsmirnova commented on src/components/Search/Search.jsx
> +  const handleInput = (e) => {
Не нравится такая реализация

2024-02-21 12:15 UTC, vsmirnova commented on src/components/Search/Search.jsx
> +        bg="var(--gray-500)"
Такие реализации сомнительны и в больших проектах приведет к печальным последствиям. Цвета лучше закладывать сразу в состояние компонента, а не передавать в пропсы.

2024-02-21 12:15 UTC, vsmirnova commented on src/components/modals/ModalAddNewBook/ModalAddNewBook.jsx
> +          <Input placeholder="Название книги" onInput={handleTitleInput} value={title} required />
Надо обращать внимание на порядок пропсов. для eslint есть плагин специальный. Общепринято на большинство проектов сначала идут boolean, потом все остальные значения и в самом конце колбэки.

2024-02-21 12:15 UTC, vsmirnova commented on src/pages/BookPage/BookPage.jsx
> +              <IconButton name="edit" size="medium" onClick={handleEditBook} hoverColor="var(--blue)" />
ну тут тоже из комментариев выше. Не надо цвета так передавать

2024-02-22 17:09 UTC, HelgiMagic commented on src/components/Search/Search.jsx
> +        bg="var(--gray-500)"
Это в таске 15 делаю

2024-02-22 17:11 UTC, HelgiMagic commented on src/pages/BookPage/BookPage.jsx
> +              <IconButton name="edit" size="medium" onClick={handleEditBook} hoverColor="var(--blue)" />
тоже в 15

2024-02-22 17:39 UTC, HelgiMagic commented on src/components/Search/Search.jsx
> +  const handleInput = (e) => {
Не нравится что через dispatch сделано, или как внутри диспатч используется?

2024-02-27 09:28 UTC, vsmirnova commented on src/components/Search/Search.jsx
> +  const handleInput = (e) => {
Во-первых плохо, что на каждый onChange вызывается функция. При поиске нужно делать так, чтобы запрос на поиск обрабатывался через несколько мс после того как пользователь закончил ввод.
Во-вторых, зачем хранить в стейте какие то листы, лишние операции с массивами? Храни строку поиска и в списке по факту сразу фильтруй в компоненте списка.

2024-02-27 09:37 UTC, HelgiMagic commented on src/components/Search/Search.jsx
> +  const handleInput = (e) => {
можно было бы так, но там же потом ещё фильтрация по жанру будет

2024-02-29 09:25 UTC, vsmirnova commented on src/components/Search/Search.jsx
> +  const handleInput = (e) => {
значит еще одно поле будет или лучше объект, где ключи это параметры по которым фильтруем, а значение - это то что ищем.

2024-03-05 11:40 UTC, merged