Task14
HelgiMagic/library pull request #11
Opened 2024-02-20 10:59 UTC by HelgiMagic

2024-03-05 12:36 UTC, vsmirnova requested changes

2024-03-05 12:36 UTC, vsmirnova commented on src/components/Dropdown/Dropdown.jsx
> +    <DropDown>
Мне крайне не нравится, что ты не хочешь мыслить компонентами, не хочешь думать о расширении проекта и в целом о крупных проектах.
DropDown это общий компонент для отображения ЛЮБОГО списка, он должен быть максимально универсальным. Он должен находиться в папке ui, он должен уметь принимать список элементов для выбора.

2024-03-05 12:36 UTC, vsmirnova commented on src/components/Dropdown/Dropdown.jsx
> +      <SettingsIcon
Про порядок пропсов уже писала.  Надо уметь поддерживать порядок в коде. Остановись, поправь, сделай красиво.

2024-03-05 12:36 UTC, vsmirnova commented on src/components/Dropdown/Dropdown.jsx
> +      <List isOpen={isOpen}>
Тяжело найти адекватные слова для комментария к этому куску кода:(
Как минимум есть .map, чтоб отрендерить массив одинаковых элементов

2024-03-05 12:36 UTC, vsmirnova commented on src/functions/filterBooks.js
>    return books.filter((book) => filterConditions.every((condition) => condition(book)));
Там где нужно универсальные конструкции, пишешь слишком конкретно, а тут излишне усложняешь. 
В целом ок, но тут можно было бы и проще написать.

2024-03-05 18:46 UTC, HelgiMagic commented on src/components/Dropdown/Dropdown.jsx
> +      <SettingsIcon
по всем изменениям внёс правки

2024-03-06 12:47 UTC, vsmirnova approved these changes

2024-03-11 17:21 UTC, merged